import{startGPS,onGPS}from "./gps.js";import{dms,plusCode,bearingName}from "./coordinates.js";import{getDigiPin,isIndiaForDigiPin}from "./digipin.js";import{savePlace,getPlaces,deletePlace}from "./storage.js";import{enableCompass,onHeading,isActive}from "./compass.js";import{getWeather}from "./services/weather.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let gps=null,selected=null;
const views={home:"homeView",position:"positionView",gps:"gpsView",address:"addressView",weather:"weatherView"};
function show(v){v=views[v]?v:"home";$$(".view").forEach(x=>x.classList.remove("active"));$("#"+views[v]).classList.add("active");history.replaceState({v},"","#"+v);window.scrollTo(0,0);if(v==="position")renderSaved();if(v==="weather")renderWeather();renderAll()}
function card(a,b){return'<div class="data-card"><label>'+a+'</label><b>'+b+"</b></div>"}
function placeName(p){if(!p)return"Waiting for GPS…";if(isIndiaForDigiPin(p.lat,p.lon))return"India";return"Location"}
function renderAll(){if(!gps?.lat)return;const p=gps,d=new Date(p.time),pin=isIndiaForDigiPin(p.lat,p.lon)?getDigiPin(p.lat,p.lon):"Not available outside India",head=Number.isFinite(p.heading)?Math.round(p.heading)+"° "+bearingName(p.heading):"Unavailable",spd=Number.isFinite(p.speed)?(p.speed*3.6).toFixed(1)+" km/h":"Unavailable",name=placeName(p);$("#gpsState")?.remove();$("#globePlace").textContent=name;$("#globeTime").textContent=d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});$("#globeDate").textContent=d.toLocaleDateString([],{day:"2-digit",month:"short",year:"numeric"});$("#positionPlace").textContent=name;$("#positionLatLon").textContent=p.lat.toFixed(6)+"° "+(p.lat>=0?"N":"S")+" · "+p.lon.toFixed(6)+"° "+(p.lon>=0?"E":"W");$("#positionAccuracy").textContent="Accuracy "+Math.round(p.accuracy||0)+" m";$("#positionData").innerHTML=[card("Latitude",p.lat.toFixed(6)+"°"),card("Longitude",p.lon.toFixed(6)+"°"),card("DMS Latitude",dms(p.lat,true)),card("DMS Longitude",dms(p.lon,false)),card("Plus Code",plusCode(p.lat,p.lon)),card("DIGIPIN",pin),card("Elevation",Number.isFinite(p.altitude)?Math.round(p.altitude)+" m":"Unavailable"),card("Accuracy",Math.round(p.accuracy||0)+" m")].join("");$("#gpsData").innerHTML=[card("GPS Status","ACTIVE"),card("Location Fix","Available"),card("Accuracy",Math.round(p.accuracy||0)+" m"),card("Elevation",Number.isFinite(p.altitude)?Math.round(p.altitude)+" m":"Unavailable"),card("Speed",spd),card("Heading",head),card("Date",d.toLocaleDateString()),card("Time",d.toLocaleTimeString()),card("Time Zone",Intl.DateTimeFormat().resolvedOptions().timeZone),card("Compass",isActive()?"Active":"Not active")].join("");$("#addressStatus").textContent="GPS coordinates available · online address enrichment not configured";$("#addressData").innerHTML=[card("Latitude",p.lat.toFixed(6)),card("Longitude",p.lon.toFixed(6))].join("");$("#postalInfo").innerHTML="<div><span>DIGIPIN</span><b>"+pin+"</b></div>";drawGlobe($("#globe"),p);drawGlobe($("#positionGlobe"),p)}
function drawGlobe(c,p){if(!c||!p)return;const n=Math.min(c.clientWidth||300,c.clientHeight||300),q=devicePixelRatio||1;c.width=n*q;c.height=n*q;const x=c.getContext("2d");x.setTransform(q,0,0,q,0,0);const cx=n/2,cy=n/2,r=n*.475;x.clearRect(0,0,n,n);
const g=x.createRadialGradient(cx-r*.3,cy-r*.35,3,cx,cy,r*1.1);g.addColorStop(0,"#7bbf82");g.addColorStop(.42,"#17617d");g.addColorStop(.78,"#073453");g.addColorStop(1,"#010914");x.fillStyle=g;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.fill();
x.save();x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.clip();
const alt=solarAlt(p.lat,p.lon,new Date());x.fillStyle="rgba(0,5,16,"+(alt<0?.58:.12)+")";x.fillRect(cx-r,cy-r,r*2,r*2);
drawLand(x,cx,cy,r);drawNightLights(x,cx,cy,r);drawGrid(x,cx,cy,r);x.restore();
x.strokeStyle="rgba(101,210,255,.9)";x.lineWidth=2;x.shadowColor="rgba(65,190,255,.7)";x.shadowBlur=16;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.stroke();x.shadowBlur=0;
const px=cx+(p.lon/180)*r*.92,py=cy-(p.lat/90)*r*.92;x.fillStyle="#7dff69";x.shadowColor="#7dff69";x.shadowBlur=20;x.beginPath();x.arc(px,py,7,0,Math.PI*2);x.fill();x.shadowBlur=0;x.strokeStyle="rgba(125,255,105,.45)";x.lineWidth=2;x.beginPath();x.arc(px,py,18,0,Math.PI*2);x.stroke();
if(Math.abs(p.lat)<35&&p.lon>45&&p.lon<125){x.fillStyle="rgba(210,235,255,.78)";x.font="600 "+Math.max(12,n*.045)+"px -apple-system,sans-serif";x.textAlign="center";x.fillText("ASIA",cx+r*.16,cy-r*.22)}
}
function project(lon,lat,cx,cy,r){return[cx+(lon/180)*r*.92,cy-(lat/90)*r*.92]}
function drawLand(x,cx,cy,r){const shapes=[
{fill:"#567b56",pts:[[ -17,37],[ -5,35],[10,44],[28,50],[38,45],[43,30],[50,28],[48,14],[42,8],[30,8],[22,15],[10,10],[0,18],[-8,30]]},
{fill:"#4f7d55",pts:[[35,72],[55,70],[75,60],[92,70],[120,65],[145,52],[170,55],[175,35],[155,30],[140,38],[125,28],[112,38],[98,30],[85,38],[72,30],[58,35],[50,45],[40,48]]},
{fill:"#4d7d55",pts:[[68,30],[76,34],[82,29],[88,23],[86,18],[82,12],[76,8],[73,15],[69,20]]},
{fill:"#4b7451",pts:[[110,-10],[130,-12],[153,-20],[155,-36],[135,-39],[118,-32],[110,-20]]},
{fill:"#477450",pts:[[ -18,15],[-5,12],[10,5],[20,-5],[28,-20],[18,-35],[5,-35],[-8,-22],[-18,-5]]}
];
for(const s of shapes){x.fillStyle=s.fill;x.beginPath();s.pts.forEach((p,i)=>{const[a,b]=project(p[0],p[1],cx,cy,r);i?x.lineTo(a,b):x.moveTo(a,b)});x.closePath();x.fill()}
}
function drawNightLights(x,cx,cy,r){if(solarAlt(20,80,new Date())>-8)return;x.fillStyle="rgba(255,214,91,.75)";for(let lon=65;lon<=145;lon+=8)for(let lat=8;lat<=48;lat+=7){if((lon+lat)%3!==0){const[a,b]=project(lon,lat,cx,cy,r);x.beginPath();x.arc(a,b,1.1,0,Math.PI*2);x.fill()}}}
function drawGrid(x,cx,cy,r){x.strokeStyle="rgba(180,225,255,.10)";x.lineWidth=1;for(let lat=-60;lat<=60;lat+=30){const[a,b]=project(0,lat,cx,cy,r);x.beginPath();x.ellipse(cx,b,r*Math.cos(lat*Math.PI/180),r*.08,0,0,Math.PI*2);x.stroke()}for(let lon=-120;lon<=120;lon+=30){const[a]=project(lon,0,cx,cy,r);x.beginPath();x.ellipse(a,cy,r*.08,r,0,0,Math.PI*2);x.stroke()}}
function solarAlt(lat,lon,date){const n=date.getTime()/86400000+2440587.5-2451545,g=(357.528+.9856003*n)*Math.PI/180,L=(280.46+.9856474*n)*Math.PI/180,dec=Math.asin(Math.sin(23.4393*Math.PI/180)*Math.sin(L+1.915*Math.PI/180*Math.sin(g)+.02*Math.PI/180*Math.sin(2*g))),u=date.getUTCHours()+date.getUTCMinutes()/60,dateAngle=((u+lon/15-12)*15)*Math.PI/180;return Math.asin(Math.sin(lat*Math.PI/180)*Math.sin(dec)+Math.cos(lat*Math.PI/180)*Math.cos(dec)*Math.cos(dateAngle))*180/Math.PI}
async function renderSaved(){const el=$("#savedPlaces"),list=await getPlaces().catch(()=>[]);el.innerHTML=list.length?list.map(p=>'<button class="saved-card" data-id="'+p.id+'"><b>'+p.label+'</b><small>'+p.lat.toFixed(5)+", "+p.lon.toFixed(5)+"</small><small>"+new Date(p.time).toLocaleString()+"</small></button>").join(""):'<div class="empty-saved">No saved places yet. Save the current position below.</div>';$$(".saved-card").forEach(b=>b.onclick=()=>selected=list.find(p=>p.id===b.dataset.id)||null)}
const weatherLabels=["Feels like","Wind","Gusts","Visibility","Humidity","Clouds","UV Index","Air Quality (AQI)","Air Pressure","Dew Point","Precipitation","Chance of Rain","Sunrise","Sunset","Moon Phase"];
function renderWeather(){const g=$("#weatherGrid");g.innerHTML=weatherLabels.map(x=>'<button class="weather-card"><label>'+x+'</label><b>—</b><small>Available when connected</small></button>').join("");getWeather().then(r=>$("#weatherUpdated").textContent=r.message)}
$$("[data-view]").forEach(b=>b.onclick=()=>show(b.dataset.view));$$("[data-back]").forEach(b=>b.onclick=()=>show("home"));window.addEventListener("popstate",()=>show(location.hash.slice(1)||"home"));
$("#compassBtn").onclick=async()=>{const ok=await enableCompass();$("#compassStatus").textContent=ok?"Active":"Unavailable — tap again if iOS requests permission";$("#compassBtn").textContent=ok?"Compass Active":"Enable Compass"};onHeading(h=>{$("#headingValue").textContent=Math.round(h)+"°";$("#headingDir").textContent=bearingName(h);$("#compassStatus").textContent="Active"});
$("#saveBtn").onclick=async()=>{if(!gps)return alert("Waiting for GPS.");const s={id:crypto.randomUUID(),time:gps.time,lat:gps.lat,lon:gps.lon,accuracy:gps.accuracy,altitude:gps.altitude,speed:gps.speed,heading:gps.heading,label:"Saved Location"};await savePlace(s);selected=s;renderSaved()};
$("#shareBtn").onclick=async()=>{if(!gps)return;const text="My Location Info\n"+gps.lat.toFixed(6)+", "+gps.lon.toFixed(6);if(navigator.share){try{await navigator.share({title:"My Location Info",text})}catch{}}else navigator.clipboard?.writeText(text)};
$("#mapBtn").onclick=()=>{if(gps)location.href="https://www.google.com/maps/search/?api=1&query="+gps.lat+","+gps.lon};
$("#deleteBtn").onclick=async()=>{if(!selected)return alert("Select a saved place first.");if(confirm("Delete this saved place?")){await deletePlace(selected.id);selected=null;renderSaved()}};
$("#copyAddress").onclick=()=>navigator.clipboard?.writeText($("#addressText").textContent);$("#weatherRefresh").onclick=renderWeather;
$("#infoBtn").onclick=()=>alert("My Location Info\nGPS core works offline. Address and weather are optional online enrichment.");$("#settingsBtn").onclick=()=>alert("Settings will include units, compass behavior, API services and backup.");
onGPS(p=>{gps=p;renderAll()});window.addEventListener("online",renderAll);window.addEventListener("pageshow",()=>{if(gps)renderAll()});
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});startGPS();setInterval(()=>{if(gps){drawGlobe($("#globe"),gps);drawGlobe($("#positionGlobe"),gps)}},30000);show(location.hash.slice(1)||"home");