import{startGPS,onGPS}from "./gps.js";
import{dms,plusCode,bearingName}from "./coordinates.js";
import{getDigiPin,isIndiaForDigiPin}from "./digipin.js";
import{savePlace,getPlaces,deletePlace}from "./storage.js";
import{enableCompass,onHeading,isActive}from "./compass.js";
import{getWeather}from "./services/weather.js";
import{reverseGeocode}from "./services/location.js";
import{initGlobe,updateGlobe}from "./globe.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let gps=null,selected=null,lastGeo={lat:null,lon:null,time:0},geoBusy=false;
const views={home:"homeView",position:"positionView",gps:"gpsView",address:"addressView",weather:"weatherView"};
const homeGlobe=initGlobe($("#globe")),positionGlobe=initGlobe($("#positionGlobe"),{mini:true});
function show(v){v=views[v]?v:"home";document.body.classList.toggle("detail-mode",v!=="home");$$(".view").forEach(x=>x.classList.remove("active"));$("#"+views[v]).classList.add("active");history.replaceState({v},"","#"+v);window.scrollTo(0,0);if(v==="position")renderSaved();if(v==="weather")renderWeather();renderAll()}
function card(a,b){return'<div class="data-card"><label>'+a+"</label><b>"+b+"</b></div>"}
function placeName(p){if(!p)return"Waiting for GPS…";if(p.place)return p.place;if(p.lat>=10.1&&p.lat<=10.85&&p.lon>=75.9&&p.lon<=76.8)return"Thrissur";if(isIndiaForDigiPin(p.lat,p.lon))return"India";return"Location"}
function distanceMeters(a,b,c,d){const R=6371000,rad=Math.PI/180,la1=a*rad,la2=c*rad,dl=(c-a)*rad,dlo=(d-b)*rad,x=Math.sin(dl/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dlo/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
async function enrichPlace(p){if(geoBusy||!navigator.onLine||!p||!Number.isFinite(p.lat)||!Number.isFinite(p.lon))return;const now=Date.now();if(lastGeo.lat!==null&&(now-lastGeo.time<60000||distanceMeters(lastGeo.lat,lastGeo.lon,p.lat,p.lon)<150))return;geoBusy=true;try{const r=await reverseGeocode(p.lat,p.lon);if(r?.ok){p.place=r.label||p.place;p.address=r.address||p.address;p.postcode=r.postcode||p.postcode;lastGeo={lat:p.lat,lon:p.lon,time:Date.now()};renderAll()}}catch{}finally{geoBusy=false}}
function renderAll(){if(!gps||!Number.isFinite(gps.lat)||!Number.isFinite(gps.lon)){$("#globeWaiting")?.classList.remove("hidden");return}const p=gps,d=new Date(p.time||Date.now()),pin=isIndiaForDigiPin(p.lat,p.lon)?getDigiPin(p.lat,p.lon):"Not available outside India",head=Number.isFinite(p.heading)?Math.round(p.heading)+"° "+bearingName(p.heading):"Unavailable",spd=Number.isFinite(p.speed)&&p.speed>=0?(p.speed*3.6).toFixed(1)+" km/h":"0.0 km/h",name=placeName(p);
$("#globeWaiting")?.classList.add("hidden");$("#positionPlace").textContent=name;$("#positionLatLon").textContent=p.lat.toFixed(6)+"° "+(p.lat>=0?"N":"S")+" · "+p.lon.toFixed(6)+"° "+(p.lon>=0?"E":"W");$("#positionAccuracy").textContent="Accuracy "+(Number.isFinite(p.accuracy)?Math.round(p.accuracy):"—")+" m";
$("#positionData").innerHTML=[card("Latitude",p.lat.toFixed(6)+"°"),card("Longitude",p.lon.toFixed(6)+"°"),card("DMS Latitude",dms(p.lat,true)),card("DMS Longitude",dms(p.lon,false)),card("Plus Code",plusCode(p.lat,p.lon)),card("DIGIPIN",pin),card("Elevation",Number.isFinite(p.altitude)?Math.round(p.altitude)+" m":"Unavailable"),card("Accuracy",Number.isFinite(p.accuracy)?Math.round(p.accuracy)+" m":"Unavailable")].join("");
$("#gpsData").innerHTML=[card("GPS Status",p.error?"WAITING":"ACTIVE"),card("Location Fix",p.error?"Last fix retained":"Available"),card("Accuracy",Number.isFinite(p.accuracy)?Math.round(p.accuracy)+" m":"Unavailable"),card("Elevation",Number.isFinite(p.altitude)?Math.round(p.altitude)+" m":"Unavailable"),card("Speed",spd),card("Heading",head),card("Date",d.toLocaleDateString()),card("Time",d.toLocaleTimeString()),card("Time Zone",Intl.DateTimeFormat().resolvedOptions().timeZone),card("Compass",isActive()?"Active":"Not active")].join("");
$("#addressStatus").textContent=p.error?"GPS fix retained · address enrichment needs a connection":"GPS coordinates available · online address enrichment active when connected";$("#addressText").textContent=p.address||"Address will be available when data is connected.";$("#addressData").innerHTML=[card("Latitude",p.lat.toFixed(6)),card("Longitude",p.lon.toFixed(6)),card("Place",name)].join("");$("#postalInfo").innerHTML="<div><span>Postcode</span><b>"+(p.postcode||"—")+"</b></div><div><span>DIGIPIN</span><b>"+pin+"</b></div>";
updateGlobe($("#globe"),p);updateGlobe($("#positionGlobe"),p)}
async function renderSaved(){const el=$("#savedPlaces"),list=await getPlaces().catch(()=>[]);el.innerHTML=list.length?list.map(p=>'<button class="saved-card" data-id="'+p.id+'"><b>'+p.label+"</b><small>"+p.lat.toFixed(5)+", "+p.lon.toFixed(5)+"</small><small>"+new Date(p.time).toLocaleString()+"</small></button>").join(""):'<div class="empty-saved">No saved places yet. Save the current position below.</div>' ;$$(".saved-card").forEach(b=>b.onclick=()=>{selected=list.find(p=>p.id===b.dataset.id)||null})}
const weatherLabels=["Feels like","Wind","Gusts","Visibility","Humidity","Clouds","UV Index","Air Quality (AQI)","Air Pressure","Dew Point","Precipitation","Chance of Rain","Sunrise","Sunset","Moon Phase"];
function renderWeather(){const g=$("#weatherGrid");g.innerHTML=weatherLabels.map(x=>'<button class="weather-card"><label>'+x+"</label><b>—</b><small>Available when connected</small></button>").join("");getWeather().then(r=>$("#weatherUpdated").textContent=r.message)}
$$("[data-view]").forEach(b=>b.onclick=()=>show(b.dataset.view));$$("[data-back]").forEach(b=>b.onclick=()=>show("home"));window.addEventListener("popstate",()=>show(location.hash.slice(1)||"home"));
$("#compassBtn").onclick=async()=>{const ok=await enableCompass();$("#compassStatus").textContent=ok?"Active":"Unavailable — tap again if iOS requests permission";$("#compassBtn").textContent=ok?"Compass Active":"Enable Compass"};
onHeading(h=>{$("#headingValue").textContent=Math.round(h)+"°";$("#headingDir").textContent=bearingName(h);$("#compassStatus").textContent="Active";$("#compassRing").style.transform="rotate("+h+"deg)";$("#compassRing").style.setProperty("--heading",h+"deg")});
$("#saveBtn").onclick=async()=>{if(!gps)return alert("Waiting for GPS.");const s={id:crypto.randomUUID(),time:gps.time,lat:gps.lat,lon:gps.lon,accuracy:gps.accuracy,altitude:gps.altitude,speed:gps.speed,heading:gps.heading,label:"Saved Location"};await savePlace(s);selected=s;renderSaved()};
$("#shareBtn").onclick=async()=>{if(!gps)return;const text="My Location Info\n"+gps.lat.toFixed(6)+", "+gps.lon.toFixed(6);if(navigator.share){try{await navigator.share({title:"My Location Info",text})}catch{}}else navigator.clipboard?.writeText(text)};
$("#mapBtn").onclick=()=>{if(gps)location.href="https://www.google.com/maps/search/?api=1&query="+gps.lat+","+gps.lon};
$("#deleteBtn").onclick=async()=>{if(!selected)return alert("Select a saved place first.");if(confirm("Delete this saved place?")){await deletePlace(selected.id);selected=null;renderSaved()}};
$("#copyAddress").onclick=()=>navigator.clipboard?.writeText($("#addressText").textContent);$("#weatherRefresh").onclick=renderWeather;
$("#infoBtn").onclick=()=>alert("My Location Info\nThe Earth is a live WebGL globe. GPS remains the authoritative position and core GPS functions work offline.");$("#settingsBtn").onclick=()=>alert("Settings will include units, compass behavior, API services and backup.");
onGPS(p=>{gps=p;renderAll();enrichPlace(p)});window.addEventListener("online",()=>{renderAll();if(gps)enrichPlace(gps)});window.addEventListener("pageshow",()=>{if(gps)renderAll()});document.addEventListener("visibilitychange",()=>{if(!document.hidden)renderAll()});
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});startGPS();show(location.hash.slice(1)||"home");