import{solarDeclination}from "./astronomy.js";
const CDN="https://cdn.jsdelivr.net/npm/three-globe/example/img/";
const EARTH=CDN+"earth-blue-marble.jpg",BUMP=CDN+"earth-topology.png",SKY=CDN+"night-sky.png";
const instances=new Map(),state=new WeakMap();
function fallback(el){if(!el)return;el.classList.add("globe-fallback-host");if(!el.querySelector(".globe-fallback"))el.insertAdjacentHTML("beforeend",'<div class="globe-fallback">3D Earth is unavailable here.<br><small>GPS coordinates continue to work.</small></div>')}
function makeMarker(){const el=document.createElement("div");el.className="earth-marker";el.innerHTML='<span class="earth-marker-dot"></span><span class="earth-marker-copy"><b></b><strong></strong><small></small></span>';return el}
function updateLight(g){try{const lights=g.lights?.();if(!lights?.length)return;const dir=lights.find(x=>x&&x.isDirectionalLight);if(!dir)return;const now=new Date(),dec=solarDeclination(now),utc=now.getUTCHours()+now.getUTCMinutes()/60+now.getUTCSeconds()/3600;let subLon=-(utc*15);if(subLon>180)subLon-=360;if(subLon<-180)subLon+=360;const pos=g.getCoords(dec,subLon,1.2);dir.position.set(pos.x,pos.y,pos.z);dir.intensity=2.15}catch{}}
export function initGlobe(element,{mini=false}={}){if(!element)return null;if(instances.has(element))return instances.get(element);if(typeof window.Globe!=="function"){fallback(element);return null}try{const g=new window.Globe(element,{rendererConfig:{antialias:true,alpha:true,powerPreference:"high-performance"},waitForGlobeReady:false,animateIn:false}).globeImageUrl(EARTH).bumpImageUrl(BUMP).backgroundImageUrl(SKY).backgroundColor("#020913").showAtmosphere(true).atmosphereColor("#65cfff").atmosphereAltitude(mini?.10:.14).globeCurvatureResolution(mini?6:4).showGraticules(false).pointsData([]).pointColor(()=>"#7dff69").pointAltitude(.025).pointRadius(mini?.30:.46).pointResolution(10).pointsMerge(false).ringsData([]).ringColor(()=>["rgba(125,255,105,.95)","rgba(125,255,105,0)"]).ringMaxRadius(2.2).ringPropagationSpeed(2.2).ringRepeatPeriod(1300).ringAltitude(.012).enablePointerInteraction(true);
g.controls().enableDamping=true;g.controls().dampingFactor=.08;g.controls().autoRotate=false;g.controls().minDistance=120;g.controls().maxDistance=420;g.pointOfView({lat:20,lng:78,altitude:mini?2.55:2.28},0);
const s={g,mini,marker:null,centered:false,ready:false,lastSunUpdate:0};state.set(element,s);instances.set(element,g);g.onGlobeReady?.(()=>{s.ready=true;updateLight(g);s.lastSunUpdate=Date.now()});return g}catch{fallback(element);return null}}
export function updateGlobe(element,p){const g=instances.get(element),s=state.get(element);if(!g||!s)return;if(!p||!Number.isFinite(p.lat)||!Number.isFinite(p.lon)){if(s.marker){g.pointsData([]);g.ringsData([]);g.htmlElementsData([])}return}
const place=p.place||"Thrissur",d=new Date(p.time||Date.now()),time=d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),date=d.toLocaleDateString([],{day:"2-digit",month:"short",year:"numeric"});
if(!s.marker){s.marker=makeMarker();g.htmlElementsData([{lat:p.lat,lng:p.lon,el:s.marker}]).htmlLat(d=>d.lat).htmlLng(d=>d.lng).htmlAltitude(.025).htmlElement(d=>d.el).htmlTransitionDuration(0)}else g.htmlElementsData([{lat:p.lat,lng:p.lon,el:s.marker}]);
const b=s.marker.querySelector("b"),strong=s.marker.querySelector("strong"),small=s.marker.querySelector("small");if(b)b.textContent=place;if(strong)strong.textContent=time;if(small)small.textContent=date;
g.pointsData([{lat:p.lat,lng:p.lon}]);g.ringsData([{lat:p.lat,lng:p.lon}]);
if(!s.centered){g.pointOfView({lat:p.lat,lng:p.lon,altitude:s.mini?2.55:2.28},700);s.centered=true}
const now=Date.now();if(now-s.lastSunUpdate>30000){updateLight(g);s.lastSunUpdate=now}}
