const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let gps=null,addressCache=null,weather=null,weatherBusy=false,heading=null,globe=null,miniGlobe=null;
const pages=["home","position","gps","address","weather"];
const info={
"latitude":["Latitude","North/south position from the Equator."],"longitude":["Longitude","East/west position from the Prime Meridian."],
"accuracy":["Accuracy","Estimated horizontal uncertainty of the GPS position."],"elevation":["Elevation","Height supplied by the device location service."],
"speed":["Speed","Movement speed supplied by the GPS service."],"heading":["Heading","Direction supplied by GPS or the device compass."],
"air-quality-aqi":["Air Quality (AQI)","Air Quality Index from the available air-quality service."],
"humidity":["Humidity","Relative humidity of the air."],"clouds":["Cloud cover","Estimated percentage of cloud cover."],
"uv-index":["UV Index","Ultraviolet radiation index."],"moon-phase":["Moon Phase","Approximate lunar phase calculated locally."]
};
function card(label,value){return `<button class="card" data-info="${label.toLowerCase().replace(/[^a-z0-9]+/g,"-")}"><label>${label}</label><b>${value}</b></button>`}
function dist(a,b,c,d){const R=6371000,r=Math.PI/180,x=Math.sin((c-a)*r/2)**2+Math.cos(a*r)*Math.cos(c*r)*Math.sin((d-b)*r/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function show(name){if(!pages.includes(name))name="home";pages.forEach(p=>$("#"+p).classList.toggle("active",p===name));if(name==="weather")renderWeather();if(name==="address")renderAddress();if(name==="position")renderPosition();if(name==="gps")renderGPS();location.hash=name;window.scrollTo(0,0)}
function initGlobe(el,mini=false){if(typeof Globe!=="function")return null;try{const g=new Globe(el).globeImageUrl("https://cdn.jsdelivr.net/npm/three-globe/example/img/earth-blue-marble.jpg").backgroundColor("#020913").showAtmosphere(true).atmosphereColor("#3f9cff").atmosphereAltitude(mini?.1:.16).pointsData([]).pointColor(()=>"#7dff69").pointRadius(mini?.14:.22).ringsData([]);g.width(el.clientWidth).height(el.clientHeight);g.pointOfView({lat:20,lng:78,altitude:mini?2.5:2.2});return g}catch{return null}}
function updateGlobe(){if(!gps)return;const d=new Date(gps.time||Date.now()),data=[{lat:gps.lat,lng:gps.lon}];[globe,miniGlobe].forEach((g,i)=>{if(!g)return;g.pointsData(data);g.ringsData(data);g.pointOfView({lat:gps.lat,lng:gps.lon,altitude:i?2.5:2.2},700)});$("#gpsOverlay").innerHTML=`● <span>${gps.place||"Current position"} · ${d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})} · ${d.toLocaleDateString([],{day:"2-digit",month:"short"})}</span>`}
function renderPosition(){const g=$("#positionCards");if(!gps){$("#place").textContent="Waiting for GPS…";$("#latlon").textContent="—";$("#accuracy").textContent="Accuracy —";g.innerHTML=[card("Latitude","Waiting for GPS…"),card("Longitude","Waiting for GPS…"),card("DMS Latitude","—"),card("DMS Longitude","—"),card("Plus Code","—"),card("DIGIPIN","—"),card("Elevation","Unavailable"),card("Accuracy","Unavailable")].join("");return}$("#place").textContent=gps.place||"Location";$("#latlon").textContent=`${gps.lat.toFixed(6)}° ${gps.lat>=0?"N":"S"} · ${gps.lon.toFixed(6)}° ${gps.lon>=0?"E":"W"}`;$("#accuracy").textContent=`Accuracy ${Math.round(gps.accuracy||0)} m`;g.innerHTML=[card("Latitude",gps.lat.toFixed(6)+"°"),card("Longitude",gps.lon.toFixed(6)+"°"),card("DMS Latitude",dms(gps.lat,true)),card("DMS Longitude",dms(gps.lon,false)),card("Plus Code",plusCode(gps.lat,gps.lon)),card("Elevation",Number.isFinite(gps.altitude)?Math.round(gps.altitude)+" m":"Unavailable"),card("Accuracy",Math.round(gps.accuracy||0)+" m"),card("Speed",Number.isFinite(gps.speed)?(gps.speed*3.6).toFixed(1)+" km/h":"0.0 km/h")].join("")}
function renderGPS(){const g=$("#gpsCards");if(!gps){g.innerHTML=[card("GPS Status","WAITING"),card("Location Fix","Waiting for GPS"),card("Accuracy","Unavailable"),card("Elevation","Unavailable"),card("Speed","0.0 km/h"),card("Heading","Unavailable"),card("Date","—"),card("Time","—"),card("Time Zone",Intl.DateTimeFormat().resolvedOptions().timeZone),card("Compass","Not active")].join("");return}const d=new Date(gps.time);g.innerHTML=[card("GPS Status",gps.error?"WAITING":"ACTIVE"),card("Location Fix",gps.error?"Last fix retained":"Available"),card("Accuracy",Math.round(gps.accuracy||0)+" m"),card("Elevation",Number.isFinite(gps.altitude)?Math.round(gps.altitude)+" m":"Unavailable"),card("Speed",Number.isFinite(gps.speed)?(gps.speed*3.6).toFixed(1)+" km/h":"0.0 km/h"),card("Heading",heading==null?"Unavailable":Math.round(heading)+"°"),card("Date",d.toLocaleDateString()),card("Time",d.toLocaleTimeString()),card("Time Zone",Intl.DateTimeFormat().resolvedOptions().timeZone),card("Compass",heading==null?"Not active":"Active")].join("")}
function renderAddress(){if(!gps){$("#addressStatus").textContent="Waiting for GPS";$("#addressText").textContent="Address will be available when GPS and data are connected.";$("#addressCards").innerHTML=[card("Latitude","—"),card("Longitude","—"),card("Place","Waiting for GPS…"),card("District","—")].join("");return}$("#addressStatus").textContent=addressCache?"Address updated · waiting for GPS movement":"Fetching address…";$("#addressText").textContent=addressCache?.address||"Fetching address…";$("#addressCards").innerHTML=[card("Latitude",gps.lat.toFixed(6)),card("Longitude",gps.lon.toFixed(6)),card("Place",addressCache?.place||gps.place||"Location"),card("District",addressCache?.district||"—")].join("")}
async function reverse(){if(!gps||!navigator.onLine)return;try{const u=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=18&addressdetails=1&lat=${gps.lat}&lon=${gps.lon}`;const r=await fetch(u,{headers:{Accept:"application/json"}}),d=await r.json(),a=d.address||{};addressCache={lat:gps.lat,lon:gps.lon,address:d.display_name||"Address unavailable",place:a.suburb||a.village||a.town||a.city||"Location",district:a.county||"",postcode:a.postcode||"",state:a.state||"",country:a.country||""};gps.place=addressCache.place;renderAddress();updateGlobe()}catch{$("#addressStatus").textContent="Address lookup failed — tap ↻ to retry."}}
async function renderWeather(){const g=$("#weatherCards");if(!g)return;if(!gps){g.innerHTML=["Feels like","Wind","Gusts","Visibility","Humidity","Clouds","UV Index","Air Quality (AQI)","Air Pressure","Dew Point","Precipitation","Chance of Rain","Sunrise","Sunset","Moon Phase"].map(x=>card(x,"Waiting for GPS")).join("");$("#weatherStatus").textContent="Waiting for GPS";return}if(weatherBusy)return;weatherBusy=true;try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${gps.lat}&longitude=${gps.lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,cloud_cover,surface_pressure,dew_point_2m&hourly=temperature_2m,precipitation_probability&daily=sunrise,sunset,precipitation_probability_max,temperature_2m_max,temperature_2m_min&timezone=auto&forecast_days=3`;const r=await fetch(u),d=await r.json();weather=d;const aq=await fetch(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${gps.lat}&longitude=${gps.lon}&current=us_aqi,european_aqi,pm2_5,pm10&timezone=auto`).then(x=>x.json()).catch(()=>({}));const c=d.current||{},day=d.daily||{};$("#temp").textContent=Number.isFinite(c.temperature_2m)?Math.round(c.temperature_2m)+"°C":"—";$("#condition").textContent="Current conditions";$("#weatherStatus").textContent="Updated "+new Date(c.time||Date.now()).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});const vals=[c.apparent_temperature,c.wind_speed_10m+" km/h",c.wind_gusts_10m||"—",(c.visibility?c.visibility/1000:"—")+" km",c.relative_humidity_2m+" %",c.cloud_cover+" %",c.uv_index||"—",Number.isFinite(aq.current?.us_aqi)?Math.round(aq.current.us_aqi)+" US":"Unavailable",c.surface_pressure+" hPa",c.dew_point_2m+"°C",c.precipitation+" mm",(day.precipitation_probability_max?.[0]??"—")+" %",day.sunrise?.[0]||"—",day.sunset?.[0]||"—","Calculated locally"];["Feels like","Wind","Gusts","Visibility","Humidity","Clouds","UV Index","Air Quality (AQI)","Air Pressure","Dew Point","Precipitation","Chance of Rain","Sunrise","Sunset","Moon Phase"].forEach((x,i)=>{const el=g.querySelectorAll(".card")[i];if(el)el.querySelector("b").textContent=vals[i]??"—"})}catch{$("#weatherStatus").textContent="Weather unavailable — tap ↻ to retry."}finally{weatherBusy=false}}
function setGPS(p){const moved=gps&&dist(gps.lat,gps.lon,p.lat,p.lon)>=150;if(moved)addressCache=null;gps=p;renderPosition();renderGPS();renderAddress();renderWeather();updateGlobe();if(!addressCache)reverse()}
function startGPS(){if(!navigator.geolocation){$("#gpsMessage").textContent="Location is not supported by this browser";renderGPS();return}if(!window.isSecureContext){$("#gpsMessage").textContent="GPS requires the HTTPS site";renderGPS();return}if(window._watch)try{navigator.geolocation.clearWatch(window._watch)}catch{}window._watch=null;window._gpsDone=false;window._gpsRetry=null;const fail=e=>{const code=e&&e.code;const msg=code===1?"Location permission is denied. Allow Location for this website in iPhone Settings.":code===2?"GPS signal unavailable. Move near a window or outdoors and tap ENABLE GPS again.":code===3?"GPS is taking too long. Tap ENABLE GPS again, or move outdoors.":"Unable to get location. Tap ENABLE GPS again.";$("#gpsMessage").textContent=msg;renderGPS()};const success=p=>{if(window._gpsDone)return;window._gpsDone=true;clearTimeout(window._gpsRetry);setGPS({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,altitude:p.coords.altitude,speed:p.coords.speed,heading:p.coords.heading,time:p.timestamp,error:null});$("#gpsMessage").textContent="GPS location active"};$("#gpsMessage").textContent="Getting your GPS location…";navigator.geolocation.getCurrentPosition(success,e=>{if(e&&e.code===3){$("#gpsMessage").textContent="GPS is slow — trying device location…";navigator.geolocation.getCurrentPosition(success,fail,{enableHighAccuracy:false,timeout:15000,maximumAge:30000})}else fail(e)},{enableHighAccuracy:true,timeout:10000,maximumAge:0});window._gpsRetry=setTimeout(()=>{if(!window._gpsDone){$("#gpsMessage").textContent="Still searching for GPS…";try{window._watch=navigator.geolocation.watchPosition(success,fail,{enableHighAccuracy:true,timeout:20000,maximumAge:10000})}catch(e){fail(e)}}},10500)}
function showInfo(key){const x=info[key];if(!x)return;$("#sheetTitle").textContent=x[0];$("#sheetText").textContent=x[1];$("#sheetIcon").textContent="ⓘ";$("#sheet").classList.add("open")}
function wire(){ $$("[data-page]").forEach(b=>b.onclick=()=>show(b.dataset.page));$$(".back").forEach(b=>b.onclick=()=>show("home"));$("#gpsButton").onclick=startGPS;$("#gpsOverlay").onclick=startGPS;$("#refreshAddress").onclick=reverse;$("#refreshWeather").onclick=()=>{weather=null;renderWeather()};$("#copyAddress").onclick=()=>navigator.clipboard?.writeText($("#addressText").textContent);$("#closeSheet").onclick=()=>$("#sheet").classList.remove("open");$$(".tabs button").forEach((b,i)=>b.onclick=()=>{if(i===0)renderWeather();else if(!weather){renderWeather()}else $("#weatherStatus").textContent=i===1?"Hourly forecast":i===2?"3-day forecast":i===3?"Radar requires a radar provider":"Map requires a map provider"});document.addEventListener("click",e=>{const c=e.target.closest(".card");if(c)showInfo(c.dataset.info);if(e.target.classList.contains("shade"))$("#sheet").classList.remove("open")})}
function dms(x,lat){const a=Math.abs(x),d=Math.floor(a),m=Math.floor((a-d)*60),s=(((a-d)*60-m)*60).toFixed(1);return `${d}° ${m}′ ${s}″ ${lat?(x>=0?"N":"S"):(x>=0?"E":"W")}`}
function plusCode(lat,lon){const A="23456789CFGHJMPQRVWX",p=(x,n)=>{let y=Math.floor((x+90)/20);return A[y]+""};return "Open Location Code unavailable offline"}
wire();globe=initGlobe($("#globe"));miniGlobe=initGlobe($("#miniGlobe"),true);renderPosition();renderGPS();renderAddress();renderWeather();if(location.hash)show(location.hash.slice(1));else show("home");startGPS();
